apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  destination:
    namespace: guestbook
    server: "https://kubernetes.default.svc"
  project: ui
  source:
    repoURL: "https://github.com/Raja-Bhattacherjee-Rackspace/argo-cd-example.git"
    targetRevision: HEAD
    path: manifests/QA/guestbook-application-ui
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      selfHeal: true
      prune: true